data_root : ./data/
data_set : EuroSAT_RGB
batch_size : 32
model : vit_b_16
run_id : alpha
early_stopping_patience : 5
devices : 1
learning_rate : 0.0001
max_epochs : 1000 # Lightning default
valid_size : 2700
